# Project identification
sonar.projectKey=GaiaTools_content-accord_46ced28b-8681-4778-8646-e7a45a5626f9
sonar.organization=Gaia Tools

# Source code location
sonar.sources=src
sonar.tests=tests

# Exclusions
sonar.exclusions=**/vendor/**,**/node_modules/**
sonar.coverage.exclusions=**/tests/**,**/vendor/**

# PHP specific settings
sonar.php.coverage.reportPaths=coverage.xml

# Source encoding
sonar.sourceEncoding=UTF-8

# PHP version
sonar.php.version=8.2